### ISSUE TITLE
if/elif/else converted to dictionary. PEP8 changes

### ISSUE THREAD

**Issue by nosam1998** [digitalocean/sample-functions-python-twilio-sms#2]
## Overview
Instead of using a long if/elif/else block I've converted it to use a dictionary instead. This will also give the user an option to add/remove codes easier. This keeps the code clean and easier to read/write. I've also formatted the code to PEP8 standards.

## Things done

- PEP8 changes including (but not limited to) function name changes and spacing.
- Converted the if/elif/else block to an easily extensible and readable dictionary. This also shortens the overall code line count.

[Current PR](https://github.com/digitalocean/sample-functions-python-twilio-sms/pull/3)

**Comment by ShivaniKumar1** [comment]
Thank you!
